import type { Product } from './types';

export const products: Product[] = [
  {
    id: 'kensington-sofa',
    name: 'Kensington Chesterfield Sofa',
    description: 'A timeless classic, the Kensington Chesterfield Sofa brings a touch of British elegance to any living space. Upholstered in premium velvet with deep button tufting and rolled arms.',
    price: 1299.99,
    images: ['product-sofa-1', 'product-sofa-2', 'product-sofa-3'],
    videoUrl: 'https://www.youtube.com/watch?v=LXb3EKWsInQ',
    category: 'Sofas',
    style: 'Classic',
    material: 'Velvet, Oak',
    brand: 'Heirloom Collective',
    dimensions: { width: 220, height: 76, depth: 95 },
    weight: 65, // kg
    assembly: 'Legs to be attached',
    care: 'Professional clean only. Blot spills immediately with a dry cloth.',
    dimensionsPdfUrl: '/pdfs/kensington-sofa-dimensions.pdf',
    reviews: [
      { id: 'r1', author: 'Eleanor P.', rating: 5, comment: "Absolutely stunning sofa, the centrepiece of our living room. Superb quality.", date: '2023-10-15' },
      { id: 'r2', author: 'James B.', rating: 4, comment: "Very comfortable and looks fantastic. Delivery was a bit slow, but worth the wait.", date: '2023-09-22' },
    ],
    questions: [
        { id: 'q1', question: 'Is the velvet pet-friendly?', answer: 'The velvet is durable, but we recommend regular cleaning if you have pets. It is not scratch-proof.', author: 'Sarah K.', date: '2023-11-05' },
        { id: 'q2', question: 'What is the seat cushion filling?', answer: null, author: 'David L.', date: '2023-11-20' },
    ],
    badge: 'Best Seller',
    swatches: [
        { color: 'Emerald Green', hex: '#285238' },
        { color: 'Royal Blue', hex: '#4169E1' },
        { color: 'Charcoal Grey', hex: '#36454F' },
    ],
    warranty: '5-year frame and spring guarantee',
  },
  {
    id: 'cotswold-table',
    name: 'Cotswold Farmhouse Dining Table',
    description: 'Gather your family around this beautiful solid oak dining table. The rustic finish and sturdy construction make it perfect for both everyday meals and special occasions.',
    price: 749.00,
    images: ['product-table-1', 'product-table-2'],
    category: 'Tables',
    style: 'Rustic',
    material: 'Solid Oak',
    brand: 'The Oak & Anvil',
    dimensions: { width: 180, height: 75, depth: 90 },
    weight: 70,
    assembly: 'Full assembly required',
    care: 'Wipe with a soft, damp cloth. Avoid harsh chemicals.',
    reviews: [
      { id: 'r3', author: 'Sophie T.', rating: 5, comment: "The perfect farmhouse table. It's solid, sturdy, and has so much character.", date: '2023-11-01' },
    ],
    questions: [],
    warranty: '2-year structural guarantee',
  },
  {
    id: 'windsor-chair',
    name: 'Windsor Accent Chair',
    description: 'A modern take on a classic design. The Windsor accent chair features a sculpted back and a comfortable upholstered seat, available in a variety of contemporary colours.',
    price: 295.50,
    images: ['product-chair-1', 'product-chair-2'],
    category: 'Chairs',
    style: 'Modern',
    material: 'Ash, Fabric',
    brand: 'ScandiForm',
    dimensions: { width: 65, height: 80, depth: 70 },
    weight: 15,
    assembly: 'No assembly required',
    care: 'Spot clean fabric with a damp cloth.',
    reviews: [],
    questions: [],
    badge: 'New',
    swatches: [
        { color: 'Mustard', hex: '#FFDB58' },
        { color: 'Teal', hex: '#008080' },
        { color: 'Blush Pink', hex: '#F1ABB9' },
    ],
    warranty: '1-year manufacturers warranty',
  },
  {
    id: 'mayfair-bed',
    name: 'Mayfair Upholstered Bed Frame',
    description: 'Create a sanctuary in your bedroom with the Mayfair bed frame. Its tall, winged headboard and plush fabric provide a luxurious and inviting feel.',
    price: 899.00,
    images: ['product-bed-1', 'product-bed-2'],
    category: 'Beds',
    style: 'Classic',
    material: 'Linen, Pine',
    brand: 'Heirloom Collective',
    dimensions: { width: 160, height: 130, depth: 215 },
    weight: 80,
    assembly: 'Full assembly required',
    care: 'Vacuum headboard regularly. Professional clean for stubborn stains.',
    reviews: [
      { id: 'r4', author: 'Chloe M.', rating: 5, comment: "Feels like sleeping in a luxury hotel every night. So well made and elegant.", date: '2023-10-05' },
    ],
    questions: [],
    warranty: '10-year frame guarantee',
  },
  {
    id: 'shoreditch-sideboard',
    name: 'Shoreditch Industrial Sideboard',
    description: 'With its blend of reclaimed wood and dark metal, the Shoreditch sideboard offers ample storage and a cool, urban edge. Perfect for dining rooms or hallways.',
    price: 599.00,
    images: ['product-cabinet-1', 'product-cabinet-2'],
    category: 'Storage',
    style: 'Industrial',
    material: 'Reclaimed Pine, Steel',
    brand: 'Urban Loft',
    dimensions: { width: 150, height: 85, depth: 45 },
    weight: 55,
    assembly: 'No assembly required',
    care: 'Wipe with a dry cloth.',
    reviews: [],
    questions: [],
    badge: 'Sale',
    warranty: '1-year structural guarantee',
  },
  {
    id: 'brighton-lamp',
    name: 'Brighton Floor Lamp',
    description: 'A minimalist floor lamp that provides warm, diffused light. The slim profile and simple design make it a versatile addition to any room.',
    price: 120.00,
    images: ['product-lamp-1'],
    category: 'Lighting',
    style: 'Minimalist',
    material: 'Metal',
    brand: 'ScandiForm',
    dimensions: { width: 25, height: 155, depth: 25 },
    weight: 8,
    assembly: 'Minor assembly required',
    care: 'Wipe with a soft, dry cloth.',
    reviews: [
       { id: 'r5', author: 'Ben A.', rating: 5, comment: "Sleek and stylish. Gives off a lovely warm light.", date: '2023-11-10' },
    ],
    questions: [],
    warranty: '1-year electrical warranty',
  },
  {
    id: 'edinburgh-bookcase',
    name: 'Edinburgh Tall Bookcase',
    description: 'A stately and spacious bookcase, perfect for showcasing your library or decorative items. Made from rich mahogany with a classic finish.',
    price: 650.00,
    images: ['product-bookcase-1'],
    category: 'Storage',
    style: 'Classic',
    material: 'Mahogany',
    brand: 'Heirloom Collective',
    dimensions: { width: 100, height: 200, depth: 30 },
    weight: 45,
    assembly: 'No assembly required',
    care: 'Dust regularly with a soft cloth.',
    reviews: [],
    questions: [],
    badge: 'New',
    warranty: '3-year structural guarantee',
  },
  {
    id: 'cambridge-desk',
    name: 'Cambridge Writing Desk',
    description: 'An elegant and functional writing desk with a minimalist design. Features a smooth oak veneer top and slender metal legs.',
    price: 320.00,
    images: ['product-desk-1'],
    category: 'Tables',
    style: 'Minimalist',
    material: 'Oak Veneer, Metal',
    brand: 'ScandiForm',
    dimensions: { width: 120, height: 75, depth: 60 },
    weight: 25,
    assembly: 'Minor assembly required',
    care: 'Wipe clean with a damp cloth.',
    reviews: [],
    questions: [],
    warranty: '1-year manufacturers warranty',
  },
  {
    id: 'bath-armchair',
    name: 'Bath Velvet Armchair',
    description: 'A plush and inviting armchair upholstered in sumptuous velvet. Its compact size makes it a perfect addition to any reading nook or living space.',
    price: 380.00,
    images: ['product-armchair-1'],
    category: 'Chairs',
    style: 'Modern',
    material: 'Velvet, Pine',
    brand: 'Heirloom Collective',
    dimensions: { width: 80, height: 85, depth: 75 },
    weight: 22,
    assembly: 'Legs to be attached',
    care: 'Professional clean only.',
    reviews: [],
    questions: [],
    badge: 'Best Seller',
    swatches: [
      { color: 'Dusty Rose', hex: '#C08081' },
      { color: 'Forest Green', hex: '#228B22' },
      { color: 'Sapphire Blue', hex: '#0F52BA' },
    ],
    warranty: '2-year frame guarantee',
  },
  {
    id: 'york-coffee-table',
    name: 'York Round Coffee Table',
    description: 'A modern coffee table with a striking industrial design. Features a concrete-effect top and a black metal geometric base.',
    price: 250.00,
    images: ['product-coffee-table-1'],
    category: 'Tables',
    style: 'Industrial',
    material: 'MDF, Metal',
    brand: 'Urban Loft',
    dimensions: { width: 80, height: 45, depth: 80 },
    weight: 18,
    assembly: 'Full assembly required',
    care: 'Wipe clean with a dry cloth. Use coasters to prevent marks.',
    reviews: [],
    questions: [],
    warranty: '1-year structural guarantee',
  },
  {
    id: 'notting-hill-loveseat',
    name: 'Notting Hill Loveseat',
    description: 'Charming and compact, this loveseat is perfect for smaller spaces. Upholstered in a durable linen-blend fabric with a relaxed, modern feel.',
    price: 699.00,
    images: ['product-loveseat-1'],
    category: 'Sofas',
    style: 'Modern',
    material: 'Linen Blend, Birch',
    brand: 'ScandiForm',
    dimensions: { width: 150, height: 80, depth: 90 },
    weight: 40,
    assembly: 'Legs to be attached',
    care: 'Spot clean with a fabric cleaner.',
    reviews: [],
    questions: [],
    badge: 'New',
    warranty: '2-year frame guarantee',
  },
  {
    id: 'greenwich-ottoman',
    name: 'Greenwich Storage Ottoman',
    description: 'A versatile and practical piece for any living room. This ottoman provides extra seating, a place to rest your feet, and hidden storage.',
    price: 199.00,
    images: ['product-ottoman-1'],
    category: 'Storage',
    style: 'Classic',
    material: 'Faux Leather, Wood',
    brand: 'Heirloom Collective',
    dimensions: { width: 100, height: 45, depth: 50 },
    weight: 15,
    assembly: 'No assembly required',
    care: 'Wipe clean with a damp cloth.',
    reviews: [],
    questions: [],
    warranty: '1-year warranty',
  },
  {
    id: 'chelsea-console-table',
    name: 'Chelsea Console Table',
    description: 'A sleek and minimalist console table that adds style to any hallway. Features a slim metal frame and a glass top.',
    price: 210.00,
    images: ['product-console-table-1'],
    category: 'Tables',
    style: 'Minimalist',
    material: 'Glass, Steel',
    brand: 'ScandiForm',
    dimensions: { width: 110, height: 80, depth: 35 },
    weight: 12,
    assembly: 'Minor assembly required',
    care: 'Clean glass with a suitable glass cleaner.',
    reviews: [],
    questions: [],
    warranty: '1-year manufacturers warranty',
  },
  {
    id: 'stratford-dining-chair',
    name: 'Stratford Dining Chair',
    description: 'A comfortable and stylish dining chair with a curved backrest and upholstered seat. Sold as a pair.',
    price: 250.00,
    images: ['product-dining-chair-1'],
    category: 'Chairs',
    style: 'Modern',
    material: 'Fabric, Oak',
    brand: 'The Oak & Anvil',
    dimensions: { width: 50, height: 85, depth: 55 },
    weight: 7,
    assembly: 'No assembly required',
    care: 'Spot clean fabric.',
    reviews: [],
    questions: [],
    badge: 'Sale',
    warranty: '1-year warranty',
  },
  {
    id: 'richmond-mirror',
    name: 'Richmond Floor Mirror',
    description: 'A large, elegant floor mirror with a beautifully ornate frame. Perfect for adding a sense of light and space to a bedroom or living area.',
    price: 180.00,
    images: ['product-floor-mirror-1'],
    category: 'Lighting',
    style: 'Classic',
    material: 'Glass, Wood Composite',
    brand: 'Heirloom Collective',
    dimensions: { width: 70, height: 180, depth: 5 },
    weight: 20,
    assembly: 'No assembly required. Can be wall-mounted or leaned.',
    care: 'Clean with a soft, dry cloth and glass cleaner.',
    reviews: [],
    questions: [],
    warranty: '1-year warranty',
  },
  {
    id: 'camden-bar-stool',
    name: 'Camden Bar Stool',
    description: 'A rustic bar stool combining a solid wood seat with a sturdy metal frame. Perfect for kitchen islands and home bars.',
    price: 95.00,
    images: ['product-bar-stool-1'],
    category: 'Chairs',
    style: 'Rustic',
    material: 'Pine, Steel',
    brand: 'Urban Loft',
    dimensions: { width: 40, height: 75, depth: 40 },
    weight: 6,
    assembly: 'No assembly required',
    care: 'Wipe clean with a damp cloth.',
    reviews: [],
    questions: [],
    warranty: '1-year structural guarantee',
  },
  {
    id: 'cotswold-chest-of-drawers',
    name: 'Cotswold Chest of Drawers',
    description: 'A charming and practical chest of drawers, crafted from solid oak. Features five spacious drawers with classic metal handles.',
    price: 550.00,
    images: ['product-chest-of-drawers-1'],
    category: 'Storage',
    style: 'Rustic',
    material: 'Solid Oak',
    brand: 'The Oak & Anvil',
    dimensions: { width: 90, height: 120, depth: 45 },
    weight: 50,
    assembly: 'No assembly required',
    care: 'Wipe with a soft, damp cloth.',
    reviews: [],
    questions: [],
    warranty: '2-year structural guarantee',
  },
  {
    id: 'manchester-tv-stand',
    name: 'Manchester TV Stand',
    description: 'An industrial-style TV stand with open shelving and a cabinet for media storage. The combination of wood and metal creates a bold statement.',
    price: 399.00,
    images: ['product-tv-stand-1'],
    category: 'Storage',
    style: 'Industrial',
    material: 'Mango Wood, Steel',
    brand: 'Urban Loft',
    dimensions: { width: 140, height: 50, depth: 40 },
    weight: 35,
    assembly: 'No assembly required',
    care: 'Wipe with a dry cloth.',
    reviews: [],
    questions: [],
    badge: 'Best Seller',
    warranty: '1-year structural guarantee',
  },
  {
    id: 'soho-pendant-light',
    name: 'Soho Pendant Light',
    description: 'A modern, geometric pendant light that creates a stunning focal point over a dining table or kitchen island. Finished in matte black metal.',
    price: 150.00,
    images: ['product-pendant-light-1'],
    category: 'Lighting',
    style: 'Modern',
    material: 'Metal',
    brand: 'ScandiForm',
    dimensions: { width: 45, height: 45, depth: 45 },
    weight: 3,
    assembly: 'Requires professional installation.',
    care: 'Dust with a soft, dry cloth.',
    reviews: [],
    questions: [],
    warranty: '1-year electrical warranty',
  },
  {
    id: 'oxford-bedside-table',
    name: 'Oxford Bedside Table',
    description: 'A classic and sturdy bedside table with two drawers for convenient storage. Painted in a soft grey with elegant metal handles.',
    price: 130.00,
    images: ['product-bedside-table-1'],
    category: 'Tables',
    style: 'Classic',
    material: 'Pine, MDF',
    brand: 'Heirloom Collective',
    dimensions: { width: 45, height: 60, depth: 40 },
    weight: 10,
    assembly: 'No assembly required',
    care: 'Wipe clean with a damp cloth.',
    reviews: [],
    questions: [],
    warranty: '1-year warranty',
  }
];

export const productCategories = Array.from(new Set(products.map(p => p.category)));
export const productStyles = Array.from(new Set(products.map(p => p.style)));
export const productMaterials = Array.from(new Set(products.map(p => p.material)));
export const productBrands = Array.from(new Set(products.map(p => p.brand)));
